<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<title>ADMINISTRATOR</title>
</head>

<body>
<form name="form1" method="post" action="admss1.php?admid=$admid&admpwd=$admpwd">
  <p>請輸入管理帳號 
    <input name="admid" type="text" id="admid">
  </p>
  <p>請輸入管理密碼 
    <input name="admpwd" type="password" id="admpwd">
  </p>
  <p>
    <input type="submit" name="Submit" value="送出">
  </p>
</form>
</body>
</html>
