<?php require ("admcheck.php");?> 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<title>ADMIN管理商品</title>
</head>

<body>
<?php include("upbar.php")?>
<p><a href="addprd.php">加入商品-管理員新增商品進入</a> </p>
<p><a href="admsdprd.php">刪除修改-管理員修改商品內容</a></p>
<p><a href="viewprd.php">檢視全部訂單-所有訂單報表列出</a></p>
<p><a href="admviewprd.php">訂單出貨處理-處理尚未出貨的訂單,處理完在NO上按可變YES</a></p>
<p><a href="admvi.php">檢視會員資料-會員名策的清單</a></p>
<p><a href="admvp.php">修改會員資料-管理員刪除會員或修改</a></p>
</body>
</html>
