<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<title>環保購物袋</title>
</head>

<body bgcolor="#FEFFDD">
<?php include("upbar.php")?>
<p><font color="#333399" size="+4">歡迎使用eZ!電子商城</font></p>施工中
<P><A href="schoola.zip"><font color=green>下載打包好的PHP原始碼</font></A>

<p>商品介紹可在購物車中看到</p>
<p>SU<A href="admin1.php">SU</A>SU就是UNIX系統中Super User的意思</p>
<P>&nbsp;Copyleft &nbsp; 2003/04/29&nbsp;作者:顏伯諴&nbsp;&nbsp;&nbsp;&nbsp;GNU&nbsp;GPL</P>
<P>聯絡信箱 <a href="mailto:melix@ms9.url.com.tw">melix@ms9.url.com.tw</a></P>
<p>任何人得不經原作者同意自行修改程式碼並加以散佈</P>
<P>用於商業行為同樣免費但必須開放原始碼及使用GPL授權</P>
</body>
</html>
