



<table width="75%" border="1" align="center" cellpadding="1" cellspacing="0" bordercolor="#996600" bgcolor="#FDF0FD">
  <tr> 
    <td width="93" height="20"><a href="index.php">購物首頁</a></td>
    <td width="93"><a href="shop.php">購買產品</a></td>
    <td width="93"><a href="adduser.php">加入會員</a></td>
    <td width="93"><a href="mdfbyuser.php">修改資料</a></td>
    <td width="93"><a href="#">尚未完工</a></td>
    <td width="96"><a href="#" ></a>尚未開放</td>
  </tr>
</table>

